Add python program to measure cycle time of piBridge [REVPI-2787]
RevolutionPi/kpi-utils pull request #1
Opened 2022-11-07 10:38 UTC by naruxde

New script and documentation

2022-11-07 11:55 UTC, nbuchwitz requested changes

2022-11-07 11:55 UTC, nbuchwitz commented on pibridge_cycle_time/pibridge-cycle-time
> +    if not pargs.batch and (ct.first or not ct.var.count % 50):  # Refresh display on first run and every 500 ms
flake8: line too long (112 > 79 characters)

2022-11-07 11:55 UTC, nbuchwitz commented on pibridge_cycle_time/pibridge-cycle-time
> +        q_display.put_nowait(tuple(ct.var.ts.values()))  # Create a copy of dict values (mutable)
flake8: line too long (97 > 79 characters)

2022-11-07 11:55 UTC, nbuchwitz commented on pibridge_cycle_time/pibridge-cycle-time
> +    "mean_ms": round(sum(ct_result.var.ts.values()) / len(ct_result.var.ts.values()), 2),
flake8: line too long (89 > 79 characters)

2022-11-07 11:55 UTC, nbuchwitz commented on pibridge_cycle_time/pibridge-cycle-time
> +
flake8: blank line contains whitespace

2022-11-07 11:55 UTC, nbuchwitz commented on pibridge_cycle_time/pibridge-cycle-time
> +
flake8: blank line contains whitespace

2022-11-07 12:06 UTC, iluminat23 commented on README.md
> +Collection of utilities for measuring key performance issues from the user's
key performance indicators

2022-11-07 14:06 UTC, hjokunbus reviewed
I generally suggest more expressive variable names. https://realpython.com/python-pep8/#how-to-choose-names

2022-11-07 16:16 UTC, naruxde commented on README.md
> +# kpi-utils
+1

2022-11-08 14:27 UTC, iluminat23 commented on pibridge_cycle_time/pibridge-cycle-time
> +__copyright__ = "Copyright (C) KUNBUS GmbH, Heerweg 15C, 73770 Denkendorf, Germany"
Is "Copyright (C) KUNBUS GmbH" not enough? In our other packages we just use this

2022-11-08 14:28 UTC, iluminat23 commented on pibridge_cycle_time/pibridge-cycle-time
> +__license__ = "GPLv3"
IS GPLv3 mandatory? Normally we use GPLv2 or MIT as GPLv3 is problematic when used on embedded devices.

2022-11-08 16:59 UTC, iluminat23 approved these changes

2022-11-08 16:59 UTC, merged